### ISSUE TITLE
Каким образом в объекте сделать так, чтоб состав полей различался?

### ISSUE THREAD

**Issue by jframeMustaevT** [jframeMustaevT/ulmart-web#1]
<div class="card" style="width: 18rem;">
                        <img  src="..."   class="card-img-top" alt="">
                        <div class="card-body">
                            <h5 class="card-title" data-th-href="@{/view/{id}(id=${product.getId()})}">[[ ${product.getName()} ]]</h5>
                            <p class="card-text">[[ ${product.getPrice()} ]] rubles</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item" data-th-href="@{/view/{id}(id=${product.getId()})}">Color: [[ ${product.getColor()} ]]</li>

                           
                        </ul>
                        <div class="card-body">
                            <a href="#" class="card-link">See more product details</a>
                        </div>

**Comment by coursar** [comment]
`data-th-if` - исходя из этого либо показываете, либо скрываете что-то
