### ISSUE TITLE
Где поиск?

### ISSUE THREAD

**Issue by coursar** [jframeMustaevT/ulmart-web#3]
https://github.com/taxa222/ulmart-web/blob/5a9e10f1fd98ad2f1fe8e8215a76cf7d56659681/src/main/java/ru/itpark/ulmart/controller/ProductController.java#L9-L20

**Comment by jframeMustaevT** [comment]
исправлено  88f8fa01a6d942b26c028e16e2c32fe2784dca5e

**Comment by coursar** [comment]
Указанный вами коммит никак не относится к поиску,

**Comment by jframeMustaevT** [comment]
@coursar 5a9e10f1fd98ad2f1fe8e8215a76cf7d56659681

**Comment by coursar** [comment]
Не увидел в этом коммите ничего, связанного с поиском

**Comment by jframeMustaevT** [comment]
@coursar https://github.com/jframeMustaevT/ulmart-web/blob/0336783bd8c0b93f222a4f577a78257677ae00b3/src/main/java/ru/itpark/ulmart/controller/ProductController.java#L20-L26

https://github.com/jframeMustaevT/ulmart-web/blob/0336783bd8c0b93f222a4f577a78257677ae00b3/src/main/resources/templates/index.html#L45-L54
 и + в package service
