### ISSUE TITLE
Где отображение деталей по продукту?

### ISSUE THREAD

**Issue by coursar** [jframeMustaevT/ulmart-web#4]
https://github.com/taxa222/ulmart-web/blob/5a9e10f1fd98ad2f1fe8e8215a76cf7d56659681/src/main/java/ru/itpark/ulmart/controller/ProductController.java#L9-L20

**Comment by jframeMustaevT** [comment]
исправлено 88f8fa01a6d942b26c028e16e2c32fe2784dca5e

**Comment by coursar** [comment]
Указанный вами коммит никак не относится к отображению деталей по продукту

**Comment by jframeMustaevT** [comment]
@coursar afd62fa52cf6498a61e13fc78074864ea337c04e
