### ISSUE TITLE
Поправить сборку

### ISSUE THREAD

**Issue by coursar** [jframeMustaevT/ulmart-web#7]
Во всех материалах описано, что делать при той ошибке, которая у вас в Travis.

**Comment by jframeMustaevT** [comment]
@coursar 
данное решение не помогло
git update-index --chmod=+x ./mvnw
git commit -m "Permission to mvnw added"
git push


mvn install -DskipTests=true -Dgpg.skip=true -Dmaven.javadoc.skip=true -B -V
пишет,что установлено??

**Comment by jframeMustaevT** [comment]
@coursar  <img width="629" alt="Снимок экрана 2019-04-24 в 21 19 22" src="https://user-images.githubusercontent.com/47470602/56683708-c7a49f80-66d6-11e9-9afa-6fe850ca5622.png">

есть только это: не пройденный материал

**Comment by coursar** [comment]
Сделайте Git Pull
